/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
namespace studio.ClassicSample
{
	partial class ClienteCtrl
	{
		protected global::System.Web.UI.WebControls.Label ErrorLbl;
		protected global::System.Web.UI.WebControls.GridView gridView1;
		protected global::System.Web.UI.WebControls.Label Label1;
		protected global::System.Web.UI.WebControls.Label CiSchLbl;
		protected global::System.Web.UI.WebControls.TextBox CiSchTxtBx;
		protected global::System.Web.UI.WebControls.Label FechaRegSchLbl;
		protected global::System.Web.UI.WebControls.TextBox FechaRegSchTxtBx;
		protected global::System.Web.UI.WebControls.LinkButton resultsBtn;
	}
}
