/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
namespace studio.ClassicSample
{
	partial class EmpleadoPersonaCtrl
	{
		protected global::System.Web.UI.WebControls.Label ErrorLbl;
		protected global::System.Web.UI.WebControls.GridView gridView1;
		protected global::System.Web.UI.WebControls.Label Label1;
		protected global::System.Web.UI.WebControls.Label CiSchLbl;
		protected global::System.Web.UI.WebControls.TextBox CiSchTxtBx;
		protected global::System.Web.UI.WebControls.Label PmnSchLbl;
		protected global::System.Web.UI.WebControls.TextBox PmnSchTxtBx;
		protected global::System.Web.UI.WebControls.Label SexoSchLbl;
		protected global::System.Web.UI.WebControls.TextBox SexoSchTxtBx;
		protected global::System.Web.UI.WebControls.Label TelefonoSchLbl;
		protected global::System.Web.UI.WebControls.TextBox TelefonoSchTxtBx;
		protected global::System.Web.UI.WebControls.Label NombreSchLbl;
		protected global::System.Web.UI.WebControls.TextBox NombreSchTxtBx;
		protected global::System.Web.UI.WebControls.LinkButton resultsBtn;
	}
}
