/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using studio.BusinessObjects;

namespace studio.ClassicSample
{
	public partial class OrdenTrabajoCtrl : System.Web.UI.UserControl
	{
		/*This class contains basic sample UI code, to illustrate usage of the CodeTrigger generated domain objects. Replace this UI layer with your own code*/
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		private int _maxResultsCheck = 750;
		protected void Page_Load(object sender, EventArgs e)
		{
			ClearUserMessage();
		}

		protected override void OnInit(EventArgs e)
		{
			resultsBtn.Click += new EventHandler(resultsBtn_Click);
			gridView1.PageIndexChanging += new GridViewPageEventHandler(gridView1_PageIndexChanging);
			gridView1.RowDataBound += new GridViewRowEventHandler(gridView1_RowDataBound);
			gridView1.RowUpdating += new GridViewUpdateEventHandler(gridView1_RowUpdating);
			gridView1.RowDeleting += new GridViewDeleteEventHandler(gridView1_RowDeleting);
			gridView1.RowEditing += new GridViewEditEventHandler(gridView1_RowEditing);
			gridView1.RowCancelingEdit += new GridViewCancelEditEventHandler(gridView1_RowCancelingEdit);
			gridView1.RowCommand += new GridViewCommandEventHandler(gridView1_RowCommand);
		}

		void gridView1_RowDataBound(object sender, GridViewRowEventArgs e)
		{
			if (e.Row.RowType == DataControlRowType.DataRow)
			{
				DropDownList ddlCie = ((DropDownList) e.Row.FindControl("CieDropDownList"));
				ddlCie.DataSource = StaticBindings.StaticBindings.GetEmpleadoList();
				ddlCie.DataBind();
				ddlCie.SelectedIndex = ((BOOrdenTrabajo)(e.Row.DataItem)).Cie == null ? -1 : ddlCie.Items.IndexOf(ddlCie.Items.FindByValue(((BOOrdenTrabajo)(e.Row.DataItem)).Cie.ToString()));
				DropDownList ddlIdEven = ((DropDownList) e.Row.FindControl("IdEvenDropDownList"));
				ddlIdEven.DataSource = StaticBindings.StaticBindings.GetEventoList();
				ddlIdEven.DataBind();
				ddlIdEven.SelectedIndex = ((BOOrdenTrabajo)(e.Row.DataItem)).IdEven == null ? -1 : ddlIdEven.Items.IndexOf(ddlIdEven.Items.FindByValue(((BOOrdenTrabajo)(e.Row.DataItem)).IdEven.ToString()));
			}
			else if (e.Row.RowType == DataControlRowType.Footer)
			{
				DropDownList ddlCie = ((DropDownList) e.Row.FindControl("CieDropDownList"));
				ddlCie.DataSource = StaticBindings.StaticBindings.GetEmpleadoList();
				ddlCie.DataBind();
				ddlCie.SelectedIndex = -1;
				DropDownList ddlIdEven = ((DropDownList) e.Row.FindControl("IdEvenDropDownList"));
				ddlIdEven.DataSource = StaticBindings.StaticBindings.GetEventoList();
				ddlIdEven.DataBind();
				ddlIdEven.SelectedIndex = -1;
			}
		}

		private void BindEmptyRow()
		{
			List<BOOrdenTrabajo> boOrdenTrabajos = new List<BOOrdenTrabajo>() { new BOOrdenTrabajo() };
			gridView1.DataSource = boOrdenTrabajos;
			gridView1.DataBind();
			
			gridView1.Rows[0].Visible = false;
			gridView1.Rows[0].Controls.Clear();
		}

		public int LoadRecords(bool checkCount)
		{
			BOOrdenTrabajo searchBO = new BOOrdenTrabajo();
			try
			{
				if(!string.IsNullOrEmpty(CieSchTxtBx.Text)) searchBO.Cie = CieSchTxtBx.Text;
				if(!string.IsNullOrEmpty(IdEvenSchTxtBx.Text)) searchBO.IdEven = Int32.Parse(IdEvenSchTxtBx.Text);
				if(!string.IsNullOrEmpty(DescripcionSchTxtBx.Text)) searchBO.Descripcion = DescripcionSchTxtBx.Text;
				if(!string.IsNullOrEmpty(FechaOSchTxtBx.Text)) searchBO.FechaO = DateTime.Parse(FechaOSchTxtBx.Text);
				if(!string.IsNullOrEmpty(FechaESchTxtBx.Text)) searchBO.FechaE = DateTime.Parse(FechaESchTxtBx.Text);
				if(!string.IsNullOrEmpty(NroSchTxtBx.Text)) searchBO.Nro = Int64.Parse(NroSchTxtBx.Text);
				if(!string.IsNullOrEmpty(EstadoSchTxtBx.Text)) searchBO.Estado = EstadoSchTxtBx.Text;
				if(!string.IsNullOrEmpty(PorcentajeSchTxtBx.Text)) searchBO.Porcentaje = Int16.Parse(PorcentajeSchTxtBx.Text);
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected a parsing error. <br>Possible invalid input format in search fields. Exception details below.<br>" + ex.Message); return -1; }
			
			try
			{
				List<BOOrdenTrabajo> boOrdenTrabajos = null;
				int resultCount = BOOrdenTrabajo.OrdenTrabajoCollectionFromSearchFieldsCount(searchBO);
				if(checkCount && (resultCount > _maxResultsCheck))
				{
					SetUserMessage("Your current filter settings will return " + resultCount.ToString() + " records. <br>Please adjust your filter settings or increase your max search results limit(750).<br>Data has not been refreshed. ");
					BindEmptyRow();
					return -1;
				}
			
				boOrdenTrabajos = BOOrdenTrabajo.OrdenTrabajoCollectionFromSearchFields(searchBO);
				if(boOrdenTrabajos.Count == 0)
				{ BindEmptyRow(); return 0; }
				
				Session["_boOrdenTrabajos"] = boOrdenTrabajos;
				gridView1.DataSource = boOrdenTrabajos;
				gridView1.DataBind();
				return boOrdenTrabajos.Count;
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while loading records from data store. Detailed error message below:<br>" + ex.Message); return -1; }
			finally	{	}
		}

		private void resultsBtn_Click(object sender, EventArgs e)
		{
			int count = LoadRecords(true);
			if(count > -1) SetUserMessage(count.ToString() + " record(s) loaded from data store");
		}

		protected void gridView1_RowEditing(object sender, GridViewEditEventArgs e)
		{
			gridView1.EditIndex = e.NewEditIndex;
			List<BOOrdenTrabajo> boOrdenTrabajos = (List<BOOrdenTrabajo>)Session["_boOrdenTrabajos"];
			gridView1.DataSource = boOrdenTrabajos;
			gridView1.DataBind();
		}
		
		protected void gridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
		{
			List<BOOrdenTrabajo> _boOrdenTrabajos = (List<BOOrdenTrabajo>)Session["_boOrdenTrabajos"];
			BOOrdenTrabajo boOrdenTrabajo = _boOrdenTrabajos[e.RowIndex];
			try
			{
				TextBox txtbxDescripcion = (TextBox)gridView1.Rows[e.RowIndex].FindControl("DescripcionGridTxtBx");
				boOrdenTrabajo.Descripcion = string.IsNullOrEmpty(txtbxDescripcion.Text) ? null : txtbxDescripcion.Text;
				TextBox txtbxFechaO = (TextBox)gridView1.Rows[e.RowIndex].FindControl("FechaOGridTxtBx");
				boOrdenTrabajo.FechaO = string.IsNullOrEmpty(txtbxFechaO.Text) ? (DateTime?)null : DateTime.Parse(txtbxFechaO.Text);
				TextBox txtbxFechaE = (TextBox)gridView1.Rows[e.RowIndex].FindControl("FechaEGridTxtBx");
				boOrdenTrabajo.FechaE = string.IsNullOrEmpty(txtbxFechaE.Text) ? (DateTime?)null : DateTime.Parse(txtbxFechaE.Text);
				TextBox txtbxEstado = (TextBox)gridView1.Rows[e.RowIndex].FindControl("EstadoGridTxtBx");
				boOrdenTrabajo.Estado = string.IsNullOrEmpty(txtbxEstado.Text) ? null : txtbxEstado.Text;
				TextBox txtbxPorcentaje = (TextBox)gridView1.Rows[e.RowIndex].FindControl("PorcentajeGridTxtBx");
				boOrdenTrabajo.Porcentaje = string.IsNullOrEmpty(txtbxPorcentaje.Text) ? (Int16?)null : Int16.Parse(txtbxPorcentaje.Text);
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message);  return; }
			
			try{ boOrdenTrabajo.Update(); }
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message);  return; }
			finally	{	}
			
			gridView1.EditIndex = -1;
			LoadRecords(false);
			SetUserMessage("Record updated");
		}
		
		protected void gridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
		{
			List<BOOrdenTrabajo> _boOrdenTrabajos = (List<BOOrdenTrabajo>)Session["_boOrdenTrabajos"];
			BOOrdenTrabajo boOrdenTrabajo = _boOrdenTrabajos[(gridView1.PageIndex*gridView1.PageSize)+e.RowIndex];
		
			try{ boOrdenTrabajo.Delete(); }
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while deleting record. Possible foreign key issue. Detailed error message below:<br>" + ex.Message); return; }
			finally	{	}
			
			LoadRecords(false);
			SetUserMessage("Record deleted");
		}
		
		protected void gridView1_RowCommand(object sender, GridViewCommandEventArgs e)
		{
			if(e.CommandName.Equals("Insert"))
			{
				BOOrdenTrabajo boOrdenTrabajo = new BOOrdenTrabajo();
				try
				{
					DropDownList ddlCie = (DropDownList)gridView1.FooterRow.FindControl("CieDropDownList");
					if(!string.IsNullOrEmpty(ddlCie.SelectedValue)) boOrdenTrabajo.Cie = (string)ddlCie.SelectedValue;
					DropDownList ddlIdEven = (DropDownList)gridView1.FooterRow.FindControl("IdEvenDropDownList");
					if(!string.IsNullOrEmpty(ddlIdEven.SelectedValue)) boOrdenTrabajo.IdEven = Int32.Parse(ddlIdEven.SelectedValue);
					TextBox txtbxDescripcion = (TextBox)gridView1.FooterRow.FindControl("DescripcionGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxDescripcion.Text)) boOrdenTrabajo.Descripcion = txtbxDescripcion.Text;
					TextBox txtbxFechaO = (TextBox)gridView1.FooterRow.FindControl("FechaOGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxFechaO.Text)) boOrdenTrabajo.FechaO = DateTime.Parse(txtbxFechaO.Text);
					TextBox txtbxFechaE = (TextBox)gridView1.FooterRow.FindControl("FechaEGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxFechaE.Text)) boOrdenTrabajo.FechaE = DateTime.Parse(txtbxFechaE.Text);
					TextBox txtbxEstado = (TextBox)gridView1.FooterRow.FindControl("EstadoGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxEstado.Text)) boOrdenTrabajo.Estado = txtbxEstado.Text;
					TextBox txtbxPorcentaje = (TextBox)gridView1.FooterRow.FindControl("PorcentajeGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxPorcentaje.Text)) boOrdenTrabajo.Porcentaje = Int16.Parse(txtbxPorcentaje.Text);
				}
				catch(Exception ex)
				{ LoadRecords(false);  SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message); return; }
				
				try{ boOrdenTrabajo.SaveNew(); }
				catch(Exception ex)
				{ LoadRecords(false); SetUserMessage("CodeTrigger has detected an error while inserting new record. Possible foreign key violation. Detailed error message below:<br>" + ex.Message); return; }
				finally	{	}
			
				LoadRecords(false);
				SetUserMessage("New record inserted");
			}
		}
			
		protected void gridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
		{
			gridView1.EditIndex = -1;
			LoadRecords(false);
		}

		protected void gridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
		{
			gridView1.PageIndex = e.NewPageIndex;
			LoadRecords(false);
		}

		private void SetUserMessage(string msg)
		{  ErrorLbl.Text = msg; }

		private void ClearUserMessage()
		{  ErrorLbl.Text = ""; }

	}
}

