/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
namespace studio.ClassicSample
{
	partial class PaqueteCtrl
	{
		protected global::System.Web.UI.WebControls.Label ErrorLbl;
		protected global::System.Web.UI.WebControls.GridView gridView1;
		protected global::System.Web.UI.WebControls.Label Label1;
		protected global::System.Web.UI.WebControls.Label IdSchLbl;
		protected global::System.Web.UI.WebControls.TextBox IdSchTxtBx;
		protected global::System.Web.UI.WebControls.Label NombreSchLbl;
		protected global::System.Web.UI.WebControls.TextBox NombreSchTxtBx;
		protected global::System.Web.UI.WebControls.Label PrecioSchLbl;
		protected global::System.Web.UI.WebControls.TextBox PrecioSchTxtBx;
		protected global::System.Web.UI.WebControls.Label DescuentoSchLbl;
		protected global::System.Web.UI.WebControls.TextBox DescuentoSchTxtBx;
		protected global::System.Web.UI.WebControls.Label PrecioTotalSchLbl;
		protected global::System.Web.UI.WebControls.TextBox PrecioTotalSchTxtBx;
		protected global::System.Web.UI.WebControls.Label GenericoSchLbl;
		protected global::System.Web.UI.WebControls.TextBox GenericoSchTxtBx;
		protected global::System.Web.UI.WebControls.LinkButton resultsBtn;
	}
}
