/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using studio.BusinessObjects;

namespace studio.ClassicSample
{
	public partial class PersonaCtrl : System.Web.UI.UserControl
	{
		/*This class contains basic sample UI code, to illustrate usage of the CodeTrigger generated domain objects. Replace this UI layer with your own code*/
		/*WARNING - This class was generated by CodeTrigger. Changes to this file may cause incorrect behaviour and will be lost when the code is regenerated*/
		private int _maxResultsCheck = 750;
		protected void Page_Load(object sender, EventArgs e)
		{
			ClearUserMessage();
		}

		protected override void OnInit(EventArgs e)
		{
			resultsBtn.Click += new EventHandler(resultsBtn_Click);
			gridView1.PageIndexChanging += new GridViewPageEventHandler(gridView1_PageIndexChanging);
			gridView1.RowDataBound += new GridViewRowEventHandler(gridView1_RowDataBound);
			gridView1.RowUpdating += new GridViewUpdateEventHandler(gridView1_RowUpdating);
			gridView1.RowDeleting += new GridViewDeleteEventHandler(gridView1_RowDeleting);
			gridView1.RowEditing += new GridViewEditEventHandler(gridView1_RowEditing);
			gridView1.RowCancelingEdit += new GridViewCancelEditEventHandler(gridView1_RowCancelingEdit);
			gridView1.RowCommand += new GridViewCommandEventHandler(gridView1_RowCommand);
		}

		void gridView1_RowDataBound(object sender, GridViewRowEventArgs e)
		{
			if (e.Row.RowType == DataControlRowType.DataRow)
			{
			}
			else if (e.Row.RowType == DataControlRowType.Footer)
			{
			}
		}

		private void BindEmptyRow()
		{
			List<BOPersona> boPersonas = new List<BOPersona>() { new BOPersona() };
			gridView1.DataSource = boPersonas;
			gridView1.DataBind();
			
			gridView1.Rows[0].Visible = false;
			gridView1.Rows[0].Controls.Clear();
		}

		public int LoadRecords(bool checkCount)
		{
			BOPersona searchBO = new BOPersona();
			try
			{
				if(!string.IsNullOrEmpty(CiSchTxtBx.Text)) searchBO.Ci = CiSchTxtBx.Text;
				if(!string.IsNullOrEmpty(NombreSchTxtBx.Text)) searchBO.Nombre = NombreSchTxtBx.Text;
				if(!string.IsNullOrEmpty(APellidoPSchTxtBx.Text)) searchBO.APellidoP = APellidoPSchTxtBx.Text;
				if(!string.IsNullOrEmpty(APellidoMSchTxtBx.Text)) searchBO.APellidoM = APellidoMSchTxtBx.Text;
				if(!string.IsNullOrEmpty(DireccionSchTxtBx.Text)) searchBO.Direccion = DireccionSchTxtBx.Text;
				if(!string.IsNullOrEmpty(SexoSchTxtBx.Text)) searchBO.Sexo = bool.Parse(SexoSchTxtBx.Text);
				if(!string.IsNullOrEmpty(TelefonoSchTxtBx.Text)) searchBO.Telefono = TelefonoSchTxtBx.Text;
				if(!string.IsNullOrEmpty(EmailSchTxtBx.Text)) searchBO.Email = EmailSchTxtBx.Text;
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected a parsing error. <br>Possible invalid input format in search fields. Exception details below.<br>" + ex.Message); return -1; }
			
			try
			{
				List<BOPersona> boPersonas = null;
				int resultCount = BOPersona.PersonaCollectionFromSearchFieldsCount(searchBO);
				if(checkCount && (resultCount > _maxResultsCheck))
				{
					SetUserMessage("Your current filter settings will return " + resultCount.ToString() + " records. <br>Please adjust your filter settings or increase your max search results limit(750).<br>Data has not been refreshed. ");
					BindEmptyRow();
					return -1;
				}
			
				boPersonas = BOPersona.PersonaCollectionFromSearchFields(searchBO);
				if(boPersonas.Count == 0)
				{ BindEmptyRow(); return 0; }
				
				Session["_boPersonas"] = boPersonas;
				gridView1.DataSource = boPersonas;
				gridView1.DataBind();
				return boPersonas.Count;
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while loading records from data store. Detailed error message below:<br>" + ex.Message); return -1; }
			finally	{	}
		}

		private void resultsBtn_Click(object sender, EventArgs e)
		{
			int count = LoadRecords(true);
			if(count > -1) SetUserMessage(count.ToString() + " record(s) loaded from data store");
		}

		protected void gridView1_RowEditing(object sender, GridViewEditEventArgs e)
		{
			gridView1.EditIndex = e.NewEditIndex;
			List<BOPersona> boPersonas = (List<BOPersona>)Session["_boPersonas"];
			gridView1.DataSource = boPersonas;
			gridView1.DataBind();
		}
		
		protected void gridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
		{
			List<BOPersona> _boPersonas = (List<BOPersona>)Session["_boPersonas"];
			BOPersona boPersona = _boPersonas[e.RowIndex];
			try
			{
				TextBox txtbxNombre = (TextBox)gridView1.Rows[e.RowIndex].FindControl("NombreGridTxtBx");
				boPersona.Nombre = string.IsNullOrEmpty(txtbxNombre.Text) ? null : txtbxNombre.Text;
				TextBox txtbxAPellidoP = (TextBox)gridView1.Rows[e.RowIndex].FindControl("APellidoPGridTxtBx");
				boPersona.APellidoP = string.IsNullOrEmpty(txtbxAPellidoP.Text) ? null : txtbxAPellidoP.Text;
				TextBox txtbxAPellidoM = (TextBox)gridView1.Rows[e.RowIndex].FindControl("APellidoMGridTxtBx");
				boPersona.APellidoM = string.IsNullOrEmpty(txtbxAPellidoM.Text) ? null : txtbxAPellidoM.Text;
				TextBox txtbxDireccion = (TextBox)gridView1.Rows[e.RowIndex].FindControl("DireccionGridTxtBx");
				boPersona.Direccion = string.IsNullOrEmpty(txtbxDireccion.Text) ? null : txtbxDireccion.Text;
				TextBox txtbxSexo = (TextBox)gridView1.Rows[e.RowIndex].FindControl("SexoGridTxtBx");
				boPersona.Sexo = string.IsNullOrEmpty(txtbxSexo.Text) ? (bool?)null : bool.Parse(txtbxSexo.Text);
				TextBox txtbxTelefono = (TextBox)gridView1.Rows[e.RowIndex].FindControl("TelefonoGridTxtBx");
				boPersona.Telefono = string.IsNullOrEmpty(txtbxTelefono.Text) ? null : txtbxTelefono.Text;
				TextBox txtbxEmail = (TextBox)gridView1.Rows[e.RowIndex].FindControl("EmailGridTxtBx");
				boPersona.Email = string.IsNullOrEmpty(txtbxEmail.Text) ? null : txtbxEmail.Text;
			}
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message);  return; }
			
			try{ boPersona.Update(); }
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message);  return; }
			finally	{	}
			
			gridView1.EditIndex = -1;
			LoadRecords(false);
			SetUserMessage("Record updated");
		}
		
		protected void gridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
		{
			List<BOPersona> _boPersonas = (List<BOPersona>)Session["_boPersonas"];
			BOPersona boPersona = _boPersonas[(gridView1.PageIndex*gridView1.PageSize)+e.RowIndex];
		
			try{ boPersona.Delete(); }
			catch(Exception ex)
			{ SetUserMessage("CodeTrigger has detected an error while deleting record. Possible foreign key issue. Detailed error message below:<br>" + ex.Message); return; }
			finally	{	}
			
			LoadRecords(false);
			SetUserMessage("Record deleted");
		}
		
		protected void gridView1_RowCommand(object sender, GridViewCommandEventArgs e)
		{
			if(e.CommandName.Equals("Insert"))
			{
				BOPersona boPersona = new BOPersona();
				try
				{
					TextBox txtbxCi = (TextBox)gridView1.FooterRow.FindControl("CiGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxCi.Text)) boPersona.Ci = txtbxCi.Text;
					TextBox txtbxNombre = (TextBox)gridView1.FooterRow.FindControl("NombreGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxNombre.Text)) boPersona.Nombre = txtbxNombre.Text;
					TextBox txtbxAPellidoP = (TextBox)gridView1.FooterRow.FindControl("APellidoPGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxAPellidoP.Text)) boPersona.APellidoP = txtbxAPellidoP.Text;
					TextBox txtbxAPellidoM = (TextBox)gridView1.FooterRow.FindControl("APellidoMGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxAPellidoM.Text)) boPersona.APellidoM = txtbxAPellidoM.Text;
					TextBox txtbxDireccion = (TextBox)gridView1.FooterRow.FindControl("DireccionGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxDireccion.Text)) boPersona.Direccion = txtbxDireccion.Text;
					TextBox txtbxSexo = (TextBox)gridView1.FooterRow.FindControl("SexoGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxSexo.Text)) boPersona.Sexo = bool.Parse(txtbxSexo.Text);
					TextBox txtbxTelefono = (TextBox)gridView1.FooterRow.FindControl("TelefonoGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxTelefono.Text)) boPersona.Telefono = txtbxTelefono.Text;
					TextBox txtbxEmail = (TextBox)gridView1.FooterRow.FindControl("EmailGridNewTxtBx");
					if(!string.IsNullOrEmpty(txtbxEmail.Text)) boPersona.Email = txtbxEmail.Text;
				}
				catch(Exception ex)
				{ LoadRecords(false);  SetUserMessage("CodeTrigger has detected an error while parsing user input. Possible invalid data format. Detailed error message below:<br>" + ex.Message); return; }
				
				try{ boPersona.SaveNew(); }
				catch(Exception ex)
				{ LoadRecords(false); SetUserMessage("CodeTrigger has detected an error while inserting new record. Possible foreign key violation. Detailed error message below:<br>" + ex.Message); return; }
				finally	{	}
			
				LoadRecords(false);
				SetUserMessage("New record inserted");
			}
		}
			
		protected void gridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
		{
			gridView1.EditIndex = -1;
			LoadRecords(false);
		}

		protected void gridView1_PageIndexChanging(object sender, GridViewPageEventArgs e)
		{
			gridView1.PageIndex = e.NewPageIndex;
			LoadRecords(false);
		}

		private void SetUserMessage(string msg)
		{  ErrorLbl.Text = msg; }

		private void ClearUserMessage()
		{  ErrorLbl.Text = ""; }

	}
}

