package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private short id;
     private TipoEquipo tipoEquipo;
     private String nombre;
     private String descripcion;
     private boolean disponible;
     private Set eventos = new HashSet(0);

    public Equipo() {
    }

	
    public Equipo(short id, TipoEquipo tipoEquipo, String nombre, boolean disponible) {
        this.id = id;
        this.tipoEquipo = tipoEquipo;
        this.nombre = nombre;
        this.disponible = disponible;
    }
    public Equipo(short id, TipoEquipo tipoEquipo, String nombre, String descripcion, boolean disponible, Set eventos) {
       this.id = id;
       this.tipoEquipo = tipoEquipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.disponible = disponible;
       this.eventos = eventos;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public TipoEquipo getTipoEquipo() {
        return this.tipoEquipo;
    }
    
    public void setTipoEquipo(TipoEquipo tipoEquipo) {
        this.tipoEquipo = tipoEquipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(boolean disponible) {
        this.disponible = disponible;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


