package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private int id;
     private TipoEvento tipoEvento;
     private Date fecha;
     private String descripcion;
     private Date hora;
     private BigDecimal latitud;
     private BigDecimal longitud;
     private Set equipos = new HashSet(0);
     private Set fichaDatoses = new HashSet(0);
     private Set direccioneses = new HashSet(0);
     private Set agendas = new HashSet(0);
     private Set ordenTrabajos = new HashSet(0);
     private Set contratos = new HashSet(0);

    public Evento() {
    }

	
    public Evento(int id, TipoEvento tipoEvento, String descripcion, Date hora) {
        this.id = id;
        this.tipoEvento = tipoEvento;
        this.descripcion = descripcion;
        this.hora = hora;
    }
    public Evento(int id, TipoEvento tipoEvento, Date fecha, String descripcion, Date hora, BigDecimal latitud, BigDecimal longitud, Set equipos, Set fichaDatoses, Set direccioneses, Set agendas, Set ordenTrabajos, Set contratos) {
       this.id = id;
       this.tipoEvento = tipoEvento;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.hora = hora;
       this.latitud = latitud;
       this.longitud = longitud;
       this.equipos = equipos;
       this.fichaDatoses = fichaDatoses;
       this.direccioneses = direccioneses;
       this.agendas = agendas;
       this.ordenTrabajos = ordenTrabajos;
       this.contratos = contratos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoEvento getTipoEvento() {
        return this.tipoEvento;
    }
    
    public void setTipoEvento(TipoEvento tipoEvento) {
        this.tipoEvento = tipoEvento;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }
    public Set getFichaDatoses() {
        return this.fichaDatoses;
    }
    
    public void setFichaDatoses(Set fichaDatoses) {
        this.fichaDatoses = fichaDatoses;
    }
    public Set getDireccioneses() {
        return this.direccioneses;
    }
    
    public void setDireccioneses(Set direccioneses) {
        this.direccioneses = direccioneses;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }
    public Set getOrdenTrabajos() {
        return this.ordenTrabajos;
    }
    
    public void setOrdenTrabajos(Set ordenTrabajos) {
        this.ordenTrabajos = ordenTrabajos;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }




}


