package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0



/**
 * FichaDatos generated by hbm2java
 */
public class FichaDatos  implements java.io.Serializable {


     private FichaDatosId id;
     private Evento evento;
     private String descripcion;

    public FichaDatos() {
    }

    public FichaDatos(FichaDatosId id, Evento evento, String descripcion) {
       this.id = id;
       this.evento = evento;
       this.descripcion = descripcion;
    }
   
    public FichaDatosId getId() {
        return this.id;
    }
    
    public void setId(FichaDatosId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


