package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0



/**
 * FichaDatosId generated by hbm2java
 */
public class FichaDatosId  implements java.io.Serializable {


     private int idEven;
     private short id;

    public FichaDatosId() {
    }

    public FichaDatosId(int idEven, short id) {
       this.idEven = idEven;
       this.id = id;
    }
   
    public int getIdEven() {
        return this.idEven;
    }
    
    public void setIdEven(int idEven) {
        this.idEven = idEven;
    }
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FichaDatosId) ) return false;
		 FichaDatosId castOther = ( FichaDatosId ) other; 
         
		 return (this.getIdEven()==castOther.getIdEven())
 && (this.getId()==castOther.getId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEven();
         result = 37 * result + this.getId();
         return result;
   }   


}


