package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0



/**
 * IncluyePc generated by hbm2java
 */
public class IncluyePc  implements java.io.Serializable {


     private IncluyePcId id;
     private Paquete paquete;
     private ComponentePaquete componentePaquete;
     private short cantidad;

    public IncluyePc() {
    }

    public IncluyePc(IncluyePcId id, Paquete paquete, ComponentePaquete componentePaquete, short cantidad) {
       this.id = id;
       this.paquete = paquete;
       this.componentePaquete = componentePaquete;
       this.cantidad = cantidad;
    }
   
    public IncluyePcId getId() {
        return this.id;
    }
    
    public void setId(IncluyePcId id) {
        this.id = id;
    }
    public Paquete getPaquete() {
        return this.paquete;
    }
    
    public void setPaquete(Paquete paquete) {
        this.paquete = paquete;
    }
    public ComponentePaquete getComponentePaquete() {
        return this.componentePaquete;
    }
    
    public void setComponentePaquete(ComponentePaquete componentePaquete) {
        this.componentePaquete = componentePaquete;
    }
    public short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(short cantidad) {
        this.cantidad = cantidad;
    }




}


