package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * OrdenTrabajo generated by hbm2java
 */
public class OrdenTrabajo  implements java.io.Serializable {


     private OrdenTrabajoId id;
     private Empleado empleado;
     private Evento evento;
     private String descripcion;
     private Date fechaO;
     private Date fechaE;
     private long nro;
     private String estado;
     private short porcentaje;

    public OrdenTrabajo() {
    }

    public OrdenTrabajo(OrdenTrabajoId id, Empleado empleado, Evento evento, String descripcion, Date fechaO, Date fechaE, long nro, String estado, short porcentaje) {
       this.id = id;
       this.empleado = empleado;
       this.evento = evento;
       this.descripcion = descripcion;
       this.fechaO = fechaO;
       this.fechaE = fechaE;
       this.nro = nro;
       this.estado = estado;
       this.porcentaje = porcentaje;
    }
   
    public OrdenTrabajoId getId() {
        return this.id;
    }
    
    public void setId(OrdenTrabajoId id) {
        this.id = id;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaO() {
        return this.fechaO;
    }
    
    public void setFechaO(Date fechaO) {
        this.fechaO = fechaO;
    }
    public Date getFechaE() {
        return this.fechaE;
    }
    
    public void setFechaE(Date fechaE) {
        this.fechaE = fechaE;
    }
    public long getNro() {
        return this.nro;
    }
    
    public void setNro(long nro) {
        this.nro = nro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public short getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(short porcentaje) {
        this.porcentaje = porcentaje;
    }




}


