package Datos;
// Generated 13-05-2014 06:34:34 PM by Hibernate Tools 3.6.0



/**
 * OrdenTrabajoId generated by hbm2java
 */
public class OrdenTrabajoId  implements java.io.Serializable {


     private String cie;
     private int idEven;

    public OrdenTrabajoId() {
    }

    public OrdenTrabajoId(String cie, int idEven) {
       this.cie = cie;
       this.idEven = idEven;
    }
   
    public String getCie() {
        return this.cie;
    }
    
    public void setCie(String cie) {
        this.cie = cie;
    }
    public int getIdEven() {
        return this.idEven;
    }
    
    public void setIdEven(int idEven) {
        this.idEven = idEven;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdenTrabajoId) ) return false;
		 OrdenTrabajoId castOther = ( OrdenTrabajoId ) other; 
         
		 return ( (this.getCie()==castOther.getCie()) || ( this.getCie()!=null && castOther.getCie()!=null && this.getCie().equals(castOther.getCie()) ) )
 && (this.getIdEven()==castOther.getIdEven());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCie() == null ? 0 : this.getCie().hashCode() );
         result = 37 * result + this.getIdEven();
         return result;
   }   


}


