/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
**************************************************************/

using System;
using System.Data;
using System.Data.SqlTypes;
using System.Data.SqlClient;
using System.Configuration;

namespace studio.DataObjects
{
	public partial class DATACONN0_BaseData 
	{
		protected DATACONN0_TxConnectionProvider _connectionProvider;

		public DATACONN0_BaseData()
		{
			Init();
		}

		protected virtual void Init()
		{
		}

		public virtual DATACONN0_TxConnectionProvider ConnectionProvider
		{
			set
			{
				if(value == null)
					throw new Exception("Connection provider cannot be null");
				
				_connectionProvider = value;
			}
		}

		public static SqlConnection StaticSqlConnection
		{
			get
			{
				SqlConnection staticConnection = new SqlConnection();
				AppSettingsReader configReader = new AppSettingsReader();
				staticConnection.ConnectionString = (string)configReader.GetValue("c503680c-ed43-4098-8beb-399e1d568ac0", typeof(string));
				return staticConnection;
			}
		}
	}
}
