USE ESTUDIO;
GO

CREATE PROCEDURE INS_PERSONA (@CI_P VARCHAR (10),
							  @NOMBRE VARCHAR (30), 
							  @APELLIDO_P VARCHAR(20),
							  @APELLIDO_M VARCHAR (20),
							  @DIRECCION VARCHAR (MAX),
							  @SEXO BIT, 
							  @TELEFONO VARCHAR (15),
							  @EMAIL VARCHAR (100))
AS	
	IF(@APELLIDO_M='')	SET @APELLIDO_M=NULL
	IF(@DIRECCION='')	SET @DIRECCION=NULL
	IF(@TELEFONO='')	SET @TELEFONO=NULL
	IF(@EMAIL='')		SET @EMAIL=NULL
	INSERT INTO Persona VALUES(@CI_P,@NOMBRE,@APELLIDO_P,@APELLIDO_M,@DIRECCION,@SEXO,@TELEFONO,@EMAIL)
GO

CREATE PROCEDURE MOD_PERSONA(@CI VARCHAR(10),							
							 @DIRECCION VARCHAR(MAX), 							 
							 @TELEFONO VARCHAR (15), 
							 @EMAIL VARCHAR (100))
AS
	IF(@DIRECCION='')	SET @DIRECCION=NULL
	IF(@TELEFONO='')	SET @TELEFONO=NULL
	IF(@EMAIL='')		SET @EMAIL=NULL
	UPDATE PERSONA	SET Direccion=@DIRECCION,								 
						Telefono=@TELEFONO,
						Email=@EMAIL
	WHERE CI=@CI	
GO

CREATE PROCEDURE ELI_PERSONA(@CI_P VARCHAR (10))
AS
	DELETE Persona WHERE CI=@CI_P		 
GO

CREATE PROCEDURE BUS_PERSONA_CI(@CI_PER VARCHAR(10))
AS
	SELECT * FROM Persona WHERE CI=@CI_PER	
GO

CREATE PROCEDURE BUS_PERSONA_EMAIL(@EMAIL_PER VARCHAR(100))
AS
	IF(@EMAIL_PER='') SET @EMAIL_PER=NULL
	SELECT * FROM Persona WHERE Email IS NOT NULL AND Email=@EMAIL_PER
GO

CREATE PROCEDURE INS_EMPLEADO (@CI_E VARCHAR (10),
							   @ID_CL SMALLINT, 
							   @FECHA_N DATE,
							   @SUELDO DECIMAL(10,2)
							   )
AS
    INSERT INTO Empleado VALUES (@CI_E,@ID_CL,@FECHA_N,@SUELDO,GETDATE())    
GO

CREATE PROCEDURE MOD_EMPLEADO (@CI_E VARCHAR (10),
							   @ID_CL SMALLINT,							   
							   @SUELDO DECIMAL(10,2)
							   )
AS
    UPDATE Empleado SET IdCL=@ID_CL,Sueldo=@SUELDO
    WHERE @CI_E=CI    
GO

CREATE PROCEDURE ELI_EMPLEADO(@CI_E VARCHAR (10))
AS
   DELETE Empleado WHERE CI=@CI_E
GO

CREATE PROCEDURE BUS_EMPLEADO(@CI_E VARCHAR(100))
AS
	SELECT * FROM Empleado WHERE CI=@CI_E
GO

CREATE PROCEDURE BUS_CLIENTE(@CI_C VARCHAR(100))
AS
	SELECT * FROM Cliente WHERE CI=@CI_C 
GO

CREATE PROCEDURE INS_CARGO_LABORAL(@NOMBRE VARCHAR(30))
AS 
  INSERT INTO CargoLaboral VALUES(@NOMBRE)
GO

CREATE PROCEDURE MOD_CARGO_LABORAL(@IDCL SMALLINT, @NOMBRE VARCHAR (30))
AS
	UPDATE CARGOLABORAL SET NOMBRE=@NOMBRE WHERE ID=@IDCL
GO

CREATE PROCEDURE BUS_CARGO_LABORAL_NOMBRE(@NOMBRE VARCHAR (30))
AS
	SELECT * FROM CargoLaboral WHERE Nombre=@NOMBRE
GO