USE ESTUDIO
GO 
CREATE PROCEDURE INS_EQUIPO(@ID SMALLINT,
							@NOMBRE VARCHAR (30),
							@DESCRIPCION VARCHAR (30),
							@ESTADO BIT,
							@IDTE SMALLINT)			
AS
    IF (@DESCRIPCION='')SET @DESCRIPCION=NULL

	INSERT INTO Equipo VALUES (@ID,@NOMBRE,@DESCRIPCION,@ESTADO,@IDTE)
GO
CREATE PROCEDURE MOD_EQUIPO(@ID SMALLINT,
							@NOMBRE VARCHAR (30),
							@DESCRIPCION VARCHAR (30),
							@ESTADO BIT,
							@IDTE SMALLINT)			
AS
    IF (@DESCRIPCION='')SET @DESCRIPCION=NULL

	UPDATE Equipo SET NOMBRE=@NOMBRE,Descripcion=@DESCRIPCION,Estado=@ESTADO,IDTE=@IDTE
	WHERE ID=@ID
GO
CREATE PROCEDURE BUS_EQUIPO(@ID SMALLINT)
AS
	SELECT * FROM Equipo WHERE Id=@ID	
GO

CREATE PROCEDURE ELI_EQUIPO(@ID SMALLINT)
AS
	DELETE Equipo WHERE Id=@ID	
GO



									