USE ESTUDIO
GO 
CREATE PROCEDURE INS_TIPOEQUIPO(@ID SMALLINT,
								@NOMBRE VARCHAR (30))
AS
	INSERT INTO TipoEquipo VALUES (@ID,@NOMBRE)	
GO

CREATE PROCEDURE MOD_TIPOEQUIPO(@ID SMALLINT,
								@NOMBRE VARCHAR(30))
AS 
	UPDATE TipoEquipo SET NOMBRE=@NOMBRE WHERE ID=@ID
GO

CREATE PROCEDURE  BUS_TIPOEQUIPO(@NOMBRE VARCHAR (30))
AS
	SELECT *FROM TipoEquipo WHERE Nombre=@NOMBRE
GO	
														