/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using studio.DataObjects;

namespace studio.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOCategoriaComponente.
	///</Summary>
	public partial class BOCategoriaComponente : DATACONN0_BaseBusiness
	{
		#region member variables
		protected Int16? _id;
		protected string _nombre;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOCategoriaComponente()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Int16 id
		///</parameters>
		public BOCategoriaComponente(Int16 id)
		{
			try
			{
				DAOCategoriaComponente daoCategoriaComponente = DAOCategoriaComponente.SelectOne(id);
				_id = daoCategoriaComponente.Id;
				_nombre = daoCategoriaComponente.Nombre;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///Constructor using unique field(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///Nombre
		///</parameters>
		public BOCategoriaComponente(string nombre)
		{
			try
			{
				DAOCategoriaComponente daoCategoriaComponente = DAOCategoriaComponente.SelectOneByNombre(nombre);
				_id = daoCategoriaComponente.Id;
				_nombre = daoCategoriaComponente.Nombre;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOCategoriaComponente
		///</parameters>
		protected internal BOCategoriaComponente(DAOCategoriaComponente daoCategoriaComponente)
		{
			try
			{
				_id = daoCategoriaComponente.Id;
				_nombre = daoCategoriaComponente.Nombre;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new CategoriaComponente record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOCategoriaComponente daoCategoriaComponente = new DAOCategoriaComponente();
			RegisterDataObject(daoCategoriaComponente);
			BeginTransaction("savenewBOCategoriaComponente");
			try
			{
				daoCategoriaComponente.Nombre = _nombre;
				daoCategoriaComponente.Insert();
				CommitTransaction();
				
				_id = daoCategoriaComponente.Id;
				_nombre = daoCategoriaComponente.Nombre;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOCategoriaComponente");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one CategoriaComponente record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOCategoriaComponente
		///</parameters>
		public virtual void Update()
		{
			DAOCategoriaComponente daoCategoriaComponente = new DAOCategoriaComponente();
			RegisterDataObject(daoCategoriaComponente);
			BeginTransaction("updateBOCategoriaComponente");
			try
			{
				daoCategoriaComponente.Id = _id;
				daoCategoriaComponente.Nombre = _nombre;
				daoCategoriaComponente.Update();
				CommitTransaction();
				
				_id = daoCategoriaComponente.Id;
				_nombre = daoCategoriaComponente.Nombre;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOCategoriaComponente");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one CategoriaComponente record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOCategoriaComponente daoCategoriaComponente = new DAOCategoriaComponente();
			RegisterDataObject(daoCategoriaComponente);
			BeginTransaction("deleteBOCategoriaComponente");
			try
			{
				daoCategoriaComponente.Id = _id;
				daoCategoriaComponente.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOCategoriaComponente");
				throw;
			}
		}
		
		///<Summary>
		///CategoriaComponenteCollection
		///This method returns the collection of BOCategoriaComponente objects
		///</Summary>
		///<returns>
		///List[BOCategoriaComponente]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static List<BOCategoriaComponente> CategoriaComponenteCollection()
		{
			List<BOCategoriaComponente> boCategoriaComponenteCollection = new List<BOCategoriaComponente>();
			List<DAOCategoriaComponente> daoCategoriaComponenteCollection = DAOCategoriaComponente.SelectAll();
			
			foreach(DAOCategoriaComponente daoCategoriaComponente in daoCategoriaComponenteCollection)
				boCategoriaComponenteCollection.Add(new BOCategoriaComponente(daoCategoriaComponente));
			
			 return boCategoriaComponenteCollection;
			
		}
		
		
		///<Summary>
		///CategoriaComponenteCollectionCount
		///This method returns the collection count of BOCategoriaComponente objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 CategoriaComponenteCollectionCount()
		{
			Int32 objCount = DAOCategoriaComponente.SelectAllCount();
			return objCount;
			
		}
		
		
		public static List<BOCategoriaComponente> CategoriaComponenteCollectionFromSearchFields(BOCategoriaComponente boCategoriaComponente)
		{
			List<BOCategoriaComponente> boCategoriaComponenteCollection = new List<BOCategoriaComponente>();
			DAOCategoriaComponente daoCategoriaComponente = new DAOCategoriaComponente();
			daoCategoriaComponente.Id = boCategoriaComponente.Id;
			daoCategoriaComponente.Nombre = boCategoriaComponente.Nombre;
			List<DAOCategoriaComponente> daoCategoriaComponenteCollection = DAOCategoriaComponente.SelectAllBySearchFields(daoCategoriaComponente);
			
			foreach(DAOCategoriaComponente resdaoCategoriaComponente in daoCategoriaComponenteCollection)
				boCategoriaComponenteCollection.Add(new BOCategoriaComponente(resdaoCategoriaComponente));
			
			return boCategoriaComponenteCollection;
			
		}
		
		
		public static Int32 CategoriaComponenteCollectionFromSearchFieldsCount(BOCategoriaComponente boCategoriaComponente)
		{
			DAOCategoriaComponente daoCategoriaComponente = new DAOCategoriaComponente();
			daoCategoriaComponente.Id = boCategoriaComponente.Id;
			daoCategoriaComponente.Nombre = boCategoriaComponente.Nombre;
			Int32 objCount = DAOCategoriaComponente.SelectAllBySearchFieldsCount(daoCategoriaComponente);
			
			return objCount;
			
		}
		
		#endregion

		#region member properties
		
		public virtual Int16? Id
		{
			get
			{
				 return _id;
			}
			set
			{
				_id = value;
				_isDirty = true;
			}
		}
		
		public virtual string Nombre
		{
			get
			{
				 return _nombre;
			}
			set
			{
				_nombre = value;
				_isDirty = true;
			}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
