/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using studio.DataObjects;

namespace studio.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOEmpleado.
	///</Summary>
	public partial class BOEmpleado : DATACONN0_BaseBusiness
	{
		#region member variables
		protected string _ci;
		protected Int16? _idCL;
		protected DateTime? _fechaNac;
		protected decimal? _sueldo;
		protected DateTime? _fechaIng;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOEmpleado()
		{
		}

		///<Summary>
		///Constructor
		///Constructor using primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///string ci
		///</parameters>
		public BOEmpleado(string ci)
		{
			try
			{
				DAOEmpleado daoEmpleado = DAOEmpleado.SelectOne(ci);
				_ci = daoEmpleado.Ci;
				_idCL = daoEmpleado.IdCL;
				_fechaNac = daoEmpleado.FechaNac;
				_sueldo = daoEmpleado.Sueldo;
				_fechaIng = daoEmpleado.FechaIng;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOEmpleado
		///</parameters>
		protected internal BOEmpleado(DAOEmpleado daoEmpleado)
		{
			try
			{
				_ci = daoEmpleado.Ci;
				_idCL = daoEmpleado.IdCL;
				_fechaNac = daoEmpleado.FechaNac;
				_sueldo = daoEmpleado.Sueldo;
				_fechaIng = daoEmpleado.FechaIng;
			}
			catch
			{
				throw;
			}
		}

		///<Summary>
		///SaveNew
		///This method persists a new Empleado record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void SaveNew()
		{
			DAOEmpleado daoEmpleado = new DAOEmpleado();
			RegisterDataObject(daoEmpleado);
			BeginTransaction("savenewBOEmpleado");
			try
			{
				daoEmpleado.Ci = _ci;
				daoEmpleado.IdCL = _idCL;
				daoEmpleado.FechaNac = _fechaNac;
				daoEmpleado.Sueldo = _sueldo;
				daoEmpleado.FechaIng = _fechaIng;
				daoEmpleado.Insert();
				CommitTransaction();
				
				_ci = daoEmpleado.Ci;
				_idCL = daoEmpleado.IdCL;
				_fechaNac = daoEmpleado.FechaNac;
				_sueldo = daoEmpleado.Sueldo;
				_fechaIng = daoEmpleado.FechaIng;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("savenewBOEmpleado");
				throw;
			}
		}
		
		///<Summary>
		///Update
		///This method updates one Empleado record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOEmpleado
		///</parameters>
		public virtual void Update()
		{
			DAOEmpleado daoEmpleado = new DAOEmpleado();
			RegisterDataObject(daoEmpleado);
			BeginTransaction("updateBOEmpleado");
			try
			{
				daoEmpleado.Ci = _ci;
				daoEmpleado.IdCL = _idCL;
				daoEmpleado.FechaNac = _fechaNac;
				daoEmpleado.Sueldo = _sueldo;
				daoEmpleado.FechaIng = _fechaIng;
				daoEmpleado.Update();
				CommitTransaction();
				
				_ci = daoEmpleado.Ci;
				_idCL = daoEmpleado.IdCL;
				_fechaNac = daoEmpleado.FechaNac;
				_sueldo = daoEmpleado.Sueldo;
				_fechaIng = daoEmpleado.FechaIng;
				_isDirty = false;
			}
			catch
			{
				RollbackTransaction("updateBOEmpleado");
				throw;
			}
		}
		///<Summary>
		///Delete
		///This method deletes one Empleado record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			DAOEmpleado daoEmpleado = new DAOEmpleado();
			RegisterDataObject(daoEmpleado);
			BeginTransaction("deleteBOEmpleado");
			try
			{
				daoEmpleado.Ci = _ci;
				daoEmpleado.Delete();
				CommitTransaction();
			}
			catch
			{
				RollbackTransaction("deleteBOEmpleado");
				throw;
			}
		}
		
		///<Summary>
		///EmpleadoCollection
		///This method returns the collection of BOEmpleado objects
		///</Summary>
		///<returns>
		///List[BOEmpleado]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static List<BOEmpleado> EmpleadoCollection()
		{
			List<BOEmpleado> boEmpleadoCollection = new List<BOEmpleado>();
			List<DAOEmpleado> daoEmpleadoCollection = DAOEmpleado.SelectAll();
			
			foreach(DAOEmpleado daoEmpleado in daoEmpleadoCollection)
				boEmpleadoCollection.Add(new BOEmpleado(daoEmpleado));
			
			 return boEmpleadoCollection;
			
		}
		
		
		///<Summary>
		///EmpleadoCollectionCount
		///This method returns the collection count of BOEmpleado objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 EmpleadoCollectionCount()
		{
			Int32 objCount = DAOEmpleado.SelectAllCount();
			return objCount;
			
		}
		
		
		public static List<BOEmpleado> EmpleadoCollectionFromSearchFields(BOEmpleado boEmpleado)
		{
			List<BOEmpleado> boEmpleadoCollection = new List<BOEmpleado>();
			DAOEmpleado daoEmpleado = new DAOEmpleado();
			daoEmpleado.Ci = boEmpleado.Ci;
			daoEmpleado.IdCL = boEmpleado.IdCL;
			daoEmpleado.FechaNac = boEmpleado.FechaNac;
			daoEmpleado.Sueldo = boEmpleado.Sueldo;
			daoEmpleado.FechaIng = boEmpleado.FechaIng;
			List<DAOEmpleado> daoEmpleadoCollection = DAOEmpleado.SelectAllBySearchFields(daoEmpleado);
			
			foreach(DAOEmpleado resdaoEmpleado in daoEmpleadoCollection)
				boEmpleadoCollection.Add(new BOEmpleado(resdaoEmpleado));
			
			return boEmpleadoCollection;
			
		}
		
		
		public static Int32 EmpleadoCollectionFromSearchFieldsCount(BOEmpleado boEmpleado)
		{
			DAOEmpleado daoEmpleado = new DAOEmpleado();
			daoEmpleado.Ci = boEmpleado.Ci;
			daoEmpleado.IdCL = boEmpleado.IdCL;
			daoEmpleado.FechaNac = boEmpleado.FechaNac;
			daoEmpleado.Sueldo = boEmpleado.Sueldo;
			daoEmpleado.FechaIng = boEmpleado.FechaIng;
			Int32 objCount = DAOEmpleado.SelectAllBySearchFieldsCount(daoEmpleado);
			
			return objCount;
			
		}
		
		#endregion

		#region member properties
		
		public virtual string Ci
		{
			get
			{
				 return _ci;
			}
			set
			{
				_ci = value;
				_isDirty = true;
			}
		}
		
		public virtual Int16? IdCL
		{
			get
			{
				 return _idCL;
			}
			set
			{
				_idCL = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? FechaNac
		{
			get
			{
				 return _fechaNac;
			}
			set
			{
				_fechaNac = value;
				_isDirty = true;
			}
		}
		
		public virtual decimal? Sueldo
		{
			get
			{
				 return _sueldo;
			}
			set
			{
				_sueldo = value;
				_isDirty = true;
			}
		}
		
		public virtual DateTime? FechaIng
		{
			get
			{
				 return _fechaIng;
			}
			set
			{
				_fechaIng = value;
				_isDirty = true;
			}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
