/*************************************************************
** Class generated by CodeTrigger, Version 4.3.0.6
** CodeTrigger is an Exotechnic Corporation (UK) Ltd Product 
** This class was generated on 08/06/2014 17:05:12
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using studio.DataObjects;

namespace studio.BusinessObjects
{
	///<Summary>
	///Class definition
	///This is the definition of the class BOEmpleadoPersona.
	///</Summary>
	public partial class BOEmpleadoPersona : DATACONN0_BaseBusiness
	{
		#region member variables
		protected string _ci;
		protected string _pmn;
		protected bool? _sexo;
		protected string _telefono;
		protected string _nombre;
		protected bool _isDirty = false;
		/*collection member objects*******************/
		/*********************************************/
		#endregion

		#region class methods
		///<Summary>
		///Constructor
		///This is the default constructor
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public BOEmpleadoPersona()
		{
		}

		///<Summary>
		///Constructor
		///This constructor initializes the business object from its respective data object
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///DAOEmpleadoPersona
		///</parameters>
		protected internal BOEmpleadoPersona(DAOEmpleadoPersona daoEmpleadoPersona)
		{
			try
			{
				_ci = daoEmpleadoPersona.Ci;
				_pmn = daoEmpleadoPersona.Pmn;
				_sexo = daoEmpleadoPersona.Sexo;
				_telefono = daoEmpleadoPersona.Telefono;
				_nombre = daoEmpleadoPersona.Nombre;
			}
			catch
			{
				throw;
			}
		}

		
		///<Summary>
		///EmpleadoPersonaCollection
		///This method returns the collection of BOEmpleadoPersona objects
		///</Summary>
		///<returns>
		///List[BOEmpleadoPersona]
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static List<BOEmpleadoPersona> EmpleadoPersonaCollection()
		{
			List<BOEmpleadoPersona> boEmpleadoPersonaCollection = new List<BOEmpleadoPersona>();
			List<DAOEmpleadoPersona> daoEmpleadoPersonaCollection = DAOEmpleadoPersona.SelectAll();
			
			foreach(DAOEmpleadoPersona daoEmpleadoPersona in daoEmpleadoPersonaCollection)
				boEmpleadoPersonaCollection.Add(new BOEmpleadoPersona(daoEmpleadoPersona));
			
			 return boEmpleadoPersonaCollection;
			
		}
		
		
		///<Summary>
		///EmpleadoPersonaCollectionCount
		///This method returns the collection count of BOEmpleadoPersona objects
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 EmpleadoPersonaCollectionCount()
		{
			Int32 objCount = DAOEmpleadoPersona.SelectAllCount();
			return objCount;
			
		}
		
		
		public static List<BOEmpleadoPersona> EmpleadoPersonaCollectionFromSearchFields(BOEmpleadoPersona boEmpleadoPersona)
		{
			List<BOEmpleadoPersona> boEmpleadoPersonaCollection = new List<BOEmpleadoPersona>();
			DAOEmpleadoPersona daoEmpleadoPersona = new DAOEmpleadoPersona();
			daoEmpleadoPersona.Ci = boEmpleadoPersona.Ci;
			daoEmpleadoPersona.Pmn = boEmpleadoPersona.Pmn;
			daoEmpleadoPersona.Sexo = boEmpleadoPersona.Sexo;
			daoEmpleadoPersona.Telefono = boEmpleadoPersona.Telefono;
			daoEmpleadoPersona.Nombre = boEmpleadoPersona.Nombre;
			List<DAOEmpleadoPersona> daoEmpleadoPersonaCollection = DAOEmpleadoPersona.SelectAllBySearchFields(daoEmpleadoPersona);
			
			foreach(DAOEmpleadoPersona resdaoEmpleadoPersona in daoEmpleadoPersonaCollection)
				boEmpleadoPersonaCollection.Add(new BOEmpleadoPersona(resdaoEmpleadoPersona));
			
			return boEmpleadoPersonaCollection;
			
		}
		
		
		public static Int32 EmpleadoPersonaCollectionFromSearchFieldsCount(BOEmpleadoPersona boEmpleadoPersona)
		{
			DAOEmpleadoPersona daoEmpleadoPersona = new DAOEmpleadoPersona();
			daoEmpleadoPersona.Ci = boEmpleadoPersona.Ci;
			daoEmpleadoPersona.Pmn = boEmpleadoPersona.Pmn;
			daoEmpleadoPersona.Sexo = boEmpleadoPersona.Sexo;
			daoEmpleadoPersona.Telefono = boEmpleadoPersona.Telefono;
			daoEmpleadoPersona.Nombre = boEmpleadoPersona.Nombre;
			Int32 objCount = DAOEmpleadoPersona.SelectAllBySearchFieldsCount(daoEmpleadoPersona);
			
			return objCount;
			
		}
		
		#endregion

		#region member properties
		
		public virtual string Ci
		{
			get
			{
				 return _ci;
			}
			set
			{
				_ci = value;
				_isDirty = true;
			}
		}
		
		public virtual string Pmn
		{
			get
			{
				 return _pmn;
			}
			set
			{
				_pmn = value;
				_isDirty = true;
			}
		}
		
		public virtual bool? Sexo
		{
			get
			{
				 return _sexo;
			}
			set
			{
				_sexo = value;
				_isDirty = true;
			}
		}
		
		public virtual string Telefono
		{
			get
			{
				 return _telefono;
			}
			set
			{
				_telefono = value;
				_isDirty = true;
			}
		}
		
		public virtual string Nombre
		{
			get
			{
				 return _nombre;
			}
			set
			{
				_nombre = value;
				_isDirty = true;
			}
		}
		
		public virtual bool IsDirty
		{
			get
			{
				 return _isDirty;
			}
			set
			{
				_isDirty = value;
			}
		}
		#endregion
	}
}
